// GENERATED by Tools/generate_theme_swift.py from Content/v1/design-tokens.json — do not edit.
// theme_id: neo_tokyo_dark  content_version: 2026.09.28-1
import SwiftUI

public enum NeoTokyo {
    public static let contentVersion = "2026.09.28-1"

    public enum Surface {
        public static let base = Color(.sRGB, red: 0.0392, green: 0.0627, blue: 0.1255, opacity: 1)  // #0A1020
        public static let raised = Color(.sRGB, red: 0.0667, green: 0.1020, blue: 0.1804, opacity: 1)  // #111A2E
        public static let overlay = Color(.sRGB, red: 0.0941, green: 0.1490, blue: 0.2588, opacity: 1)  // #182642
        public static let line = Color(.sRGB, red: 0.1451, green: 0.2078, blue: 0.3529, opacity: 1)  // #25355A
        public static let sceneFade = Color(.sRGB, red: 0.0392, green: 0.0627, blue: 0.1255, opacity: 1)  // #0A1020
    }

    public enum Text {
        public static let primary = Color(.sRGB, red: 0.8941, green: 0.9137, blue: 0.9569, opacity: 1)  // #E4E9F4
        public static let secondary = Color(.sRGB, red: 0.6235, green: 0.6745, blue: 0.7843, opacity: 1)  // #9FACC8
        public static let muted = Color(.sRGB, red: 0.4196, green: 0.4784, blue: 0.6118, opacity: 1)  // #6B7A9C
        public static let onAccent = Color(.sRGB, red: 0.0392, green: 0.0627, blue: 0.1255, opacity: 1)  // #0A1020
    }

    public enum Accent {
        public static let pink = Color(.sRGB, red: 0.8784, green: 0.5451, blue: 0.6706, opacity: 1)  // #E08BAB
        public static let pinkDim = Color(.sRGB, red: 0.5412, green: 0.2392, blue: 0.3608, opacity: 1)  // #8A3D5C
        public static let blue = Color(.sRGB, red: 0.4353, green: 0.6627, blue: 0.8627, opacity: 1)  // #6FA9DC
        public static let blueDim = Color(.sRGB, red: 0.1804, green: 0.3608, blue: 0.5333, opacity: 1)  // #2E5C88
        public static let green = Color(.sRGB, red: 0.3608, green: 0.7725, blue: 0.6902, opacity: 1)  // #5CC5B0
        public static let greenDim = Color(.sRGB, red: 0.1686, green: 0.4196, blue: 0.3843, opacity: 1)  // #2B6B62
        public static let amber = Color(.sRGB, red: 0.8510, green: 0.7020, blue: 0.4157, opacity: 1)  // #D9B36A
        public static let amberDim = Color(.sRGB, red: 0.4784, green: 0.3765, blue: 0.1882, opacity: 1)  // #7A6030
        public static let coral = Color(.sRGB, red: 0.8471, green: 0.4667, blue: 0.4196, opacity: 1)  // #D8776B
        public static let coralDim = Color(.sRGB, red: 0.4784, green: 0.2275, blue: 0.2000, opacity: 1)  // #7A3A33
    }

    public enum Attribute {
        public static let strength = Color(.sRGB, red: 0.8784, green: 0.5451, blue: 0.6706, opacity: 1)  // #E08BAB
        public static let endurance = Color(.sRGB, red: 0.4353, green: 0.6627, blue: 0.8627, opacity: 1)  // #6FA9DC
        public static let knowledge = Color(.sRGB, red: 0.8510, green: 0.7020, blue: 0.4157, opacity: 1)  // #D9B36A
        public static let mindfulness = Color(.sRGB, red: 0.3608, green: 0.7725, blue: 0.6902, opacity: 1)  // #5CC5B0

        /// Color for an attribute slug from the content bundle; falls back to secondary text.
        public static func color(for id: String) -> Color {
            switch id {
            case "strength": return strength
            case "endurance": return endurance
            case "knowledge": return knowledge
            case "mindfulness": return mindfulness
            default: return NeoTokyo.Text.secondary
            }
        }
    }

    public enum Backdrop {
        public static let rainDistrict: [Color] = [Color(.sRGB, red: 0.0431, green: 0.1333, blue: 0.2000, opacity: 1), Color(.sRGB, red: 0.1098, green: 0.2902, blue: 0.4000, opacity: 1), Color(.sRGB, red: 0.2431, green: 0.4863, blue: 0.5922, opacity: 1)]
        public static let moonAlley: [Color] = [Color(.sRGB, red: 0.1020, green: 0.0706, blue: 0.0784, opacity: 1), Color(.sRGB, red: 0.2902, green: 0.1451, blue: 0.1608, opacity: 1), Color(.sRGB, red: 0.5490, green: 0.2275, blue: 0.2667, opacity: 1)]
        public static let amberRooftop: [Color] = [Color(.sRGB, red: 0.1176, green: 0.0902, blue: 0.0706, opacity: 1), Color(.sRGB, red: 0.2902, green: 0.1961, blue: 0.1333, opacity: 1), Color(.sRGB, red: 0.5412, green: 0.3961, blue: 0.2824, opacity: 1)]
        public static let shrineFalls: [Color] = [Color(.sRGB, red: 0.0549, green: 0.1373, blue: 0.2510, opacity: 1), Color(.sRGB, red: 0.1412, green: 0.3294, blue: 0.4706, opacity: 1), Color(.sRGB, red: 0.4353, green: 0.6392, blue: 0.6745, opacity: 1)]
    }

    public enum Radius {
        public static let sm: CGFloat = 6
        public static let md: CGFloat = 10
        public static let lg: CGFloat = 16
        public static let pill: CGFloat = 999
    }

    public enum Spacing {
        public static let xs: CGFloat = 4
        public static let sm: CGFloat = 8
        public static let md: CGFloat = 12
        public static let lg: CGFloat = 16
        public static let xl: CGFloat = 24
        public static let xxl: CGFloat = 32
    }

    public enum Motion {
        public static let fastMs: Double = 120
        public static let baseMs: Double = 200
        public static let rewardMs: Double = 2400
        public static let idleFrameMs: Double = 140
    }
}
