#!/usr/bin/env python3
"""Write an HTML copy inventory from the content bundle: item descriptions, the copy around quests
(not the character's speech bubbles), and every daily goal title and line.
    python3 Tools/export_copy_inventory.py [Content/v1/bundle.json] [out.html]
Chrome strings (buttons, eyebrows, state lines) live in App/Sources and are listed here by hand with their file.
"""
import html, json, sys
bundle_path = sys.argv[1] if len(sys.argv) > 1 else "Content/v1/bundle.json"
out_path = sys.argv[2] if len(sys.argv) > 2 else "copy-inventory.html"
b = json.load(open(bundle_path))
e = html.escape
items = b["items"]; quests = b["quests"]; goals = b["goal_templates"]
rewards = {r["id"]: r for r in b["rewards"]}
attrs = {a["id"]: a["display_name"] for a in b["attributes"]}

# Which quests can drop each item (via reward ids in the loot pools).
drops = {}
for q in quests:
    for tier, ids in (q.get("loot") or {}).items():
        for rid in ids:
            for g in rewards.get(rid, {}).get("grants", []):
                if g.get("type") == "item": drops.setdefault(g["item_id"], []).append((q["display_name"], tier))

def rarity(r): return f'<span class="pill {e(r)}">{e(r)}</span>'

out = [f"""<title>Chapter One Copy Inventory</title>
<style>
/* Layout: one column of three inventories, each a table that reads top to bottom; navy ground, gold for progression, white for data. */
:root {{
  --bg: #0B1020; --surface: #121A30; --line: #26314F; --fg: #E9ECF5; --muted: #9AA5C4; --gold: #E3B65A; --warn: #F08A6B;
  --common: #9AA5C4; --uncommon: #7FB4F0; --rare: #E3B65A;
  --mono: ui-monospace, "SF Mono", Menlo, Consolas, monospace; --sans: "Barlow", -apple-system, "Segoe UI", system-ui, sans-serif;
  color-scheme: dark;
}}
@media (prefers-color-scheme: light) {{ :root:not([data-theme="dark"]) {{ --bg: #F3F4F8; --surface: #FFFFFF; --line: #D7DBE8; --fg: #121A30; --muted: #56607F; --gold: #9A6F12; --warn: #B8441F; --common: #56607F; --uncommon: #2566B5; --rare: #9A6F12; color-scheme: light }} }}
:root[data-theme="light"] {{ --bg: #F3F4F8; --surface: #FFFFFF; --line: #D7DBE8; --fg: #121A30; --muted: #56607F; --gold: #9A6F12; --warn: #B8441F; --common: #56607F; --uncommon: #2566B5; --rare: #9A6F12; color-scheme: light }}
body {{ background: var(--bg); color: var(--fg); font: 15px/1.5 var(--sans); margin: 0; padding-block: 32px 64px; padding-inline: 16px; }}
main {{ max-width: 1040px; margin: 0 auto; display: grid; gap: 40px; }}
h1 {{ font-size: 28px; margin: 0 0 4px; text-wrap: balance; }}
h2 {{ font-size: 20px; margin: 0; padding-top: 8px; border-top: 1px solid var(--line); }}
h3 {{ font-size: 15px; margin: 20px 0 8px; color: var(--muted); text-transform: uppercase; letter-spacing: .08em; font-weight: 600; }}
p.lede {{ color: var(--muted); margin: 0; max-width: 65ch; }}
.meta {{ font-family: var(--mono); font-size: 12px; color: var(--muted); }}
.wrap {{ overflow-x: auto; }}
table {{ border-collapse: collapse; width: 100%; font-size: 14px; }}
th {{ text-align: left; color: var(--muted); font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: .06em; padding: 8px 10px; border-bottom: 1px solid var(--line); }}
td {{ padding: 9px 10px; border-bottom: 1px solid var(--line); vertical-align: top; }}
td.id {{ font-family: var(--mono); font-size: 12px; color: var(--muted); white-space: nowrap; }}
td.copy {{ min-width: 24ch; }}
.pill {{ font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: .06em; padding: 2px 6px; border-radius: 3px; border: 1px solid currentColor; white-space: nowrap; }}
.common {{ color: var(--common); }} .uncommon {{ color: var(--uncommon); }} .rare {{ color: var(--rare); }}
.missing {{ color: var(--warn); font-style: italic; }}
.where {{ color: var(--muted); font-size: 13px; }}
.count {{ color: var(--gold); font-variant-numeric: tabular-nums; }}
details {{ margin-top: 8px; }} summary {{ cursor: pointer; color: var(--muted); }}
ul.lines {{ margin: 4px 0 0; padding-left: 18px; }} ul.lines li {{ margin: 2px 0; }}
.var {{ font-family: var(--mono); font-size: 12px; color: var(--gold); }}
</style>
<main>
<header>
<h1>Chapter One Copy Inventory</h1>
<p class="lede">Every item description, the copy around quests, and every daily goal title and line, read straight from the bundle. Speech bubbles (depart, away, return lines) are the character's dialogue and sit in a fold at the end of each quest for reference only.</p>
<p class="meta">Content/v1/bundle.json · content_version {e(b['content_version'])} · generated by Tools/export_copy_inventory.py</p>
</header>
"""]

# 1. Items
missing = [i for i in items if not i.get("description")]
out.append(f"""<section id="items">
<h2>1 · Item descriptions <span class="count">{len(items)}</span></h2>
<p class="lede">Shown in the claim modal under the item's still and in the Room's inventory. {len(missing)} items have no description yet (flagged).</p>
<div class="wrap"><table>
<tr><th>Item</th><th>Slot</th><th>Rarity</th><th>Description</th><th>Where it drops</th></tr>""")
for i in items:
    where = "; ".join(f"{q} ({t})" for q, t in drops.get(i["id"], [])) or ("Starter kit" if i.get("starter") else '<span class="missing">not in any loot pool</span>')
    d = e(i["description"]) if i.get("description") else '<span class="missing">no description</span>'
    out.append(f"<tr><td><strong>{e(i['display_name'])}</strong><br><span class='meta'>{e(i['id'])}</span></td><td>{e(i['slot'])}</td><td>{rarity(i['rarity'])}</td><td class='copy'>{d}</td><td class='where'>{where}</td></tr>")
out.append("</table></div></section>")

# 2. Quest copy
out.append(f"""<section id="quests">
<h2>2 · Quest copy <span class="count">{len(quests)}</span> quests</h2>
<p class="lede">Per quest: the name, the explainer the character gives before the notification prompt, and the subtext under the path on the quest screen. The shared chrome (buttons, state lines, the claim modal, the notification) follows the table.</p>
<div class="wrap"><table>
<tr><th>Quest</th><th>Unlock</th><th>Notification explainer<br><span class="where">bubble on the “Begin quest” sheet, first departure only</span></th><th>Subtext<br><span class="where">under the quest path, quest screen</span></th></tr>""")
for q in quests:
    unlock = q.get("unlocked_by_milestone", "from the start")
    out.append(f"<tr><td><strong>{e(q['display_name'])}</strong><br><span class='meta'>{e(q['id'])}</span><br><span class='where'>{q.get('duration_minutes', 240)//60} h · {e(q.get('area_id',''))}</span></td><td class='id'>{e(unlock)}</td><td class='copy'>{e(q.get('notification_prompt',''))}</td><td class='copy'>{e(q.get('subtext',''))}</td></tr>")
out.append("</table></div>")
for q in quests:
    out.append(f"<details><summary>Speech bubbles for {e(q['display_name'])} (dialogue, for reference)</summary>")
    out.append("<h3>Depart</h3><ul class='lines'>" + "".join(f"<li>{e(l)}</li>" for l in q.get("depart_lines", [])) + "</ul>")
    out.append("<h3>Away</h3><ul class='lines'>" + "".join(f"<li>{e(l)}</li>" for l in q.get("away_lines", [])) + "</ul>")
    for tier, lines in (q.get("return_lines") or {}).items():
        out.append(f"<h3>Return · {e(tier)}</h3><ul class='lines'>" + "".join(f"<li>{e(l)}</li>" for l in lines) + "</ul>")
    out.append("</details>")

chrome = [
    ("Home · goals card", "GoalsCard.swift", [
        ("Eyebrow", "Training day / Rest day", "by the day's plan"),
        ("Title · locked", "Daily quest", "goals not all done"),
        ("Line · locked, no goals yet", "Goals arrive with the day.", ""),
        ("Line · locked", "One goal left to unlock it. / {n} goals left to unlock it.", ""),
        ("Title · ready", "Daily quest ready", ""),
        ("Line · ready", "All goals done. {quest name} is open.", "falls back to “The road”"),
        ("Button · ready", "Begin quest", "filled button"),
        ("Title · away", "{quest name}", "with the countdown"),
        ("Line · away", "{away bubble}", "dialogue"),
        ("Title · returned", "Quest complete", ""),
        ("Line · returned, unclaimed", "Back. Something came back too.", ""),
        ("Line · returned, claimed", "{return bubble}", "dialogue"),
        ("Button · returned, unclaimed", "Open the cache", "quiet button"),
    ]),
    ("Begin quest sheet (first departure only)", "GoalsCard.swift · QuestDepartPrompt", [
        ("Bubble", "{quest notification explainer}", "fallback: “Time to see if I can find anything useful around here. I'll be back in a few hours.”"),
        ("Button", "Enable notifications", "asks the system"),
        ("Button", "Not now", "departs silently"),
    ]),
    ("Home · scene", "HomeView.swift", [
        ("Away pill", "Away · tap to look", "over the empty road, with the countdown"),
        ("Back pill eyebrow", "Back", "with the glowing cache"),
        ("Back pill", "Open the cache", ""),
    ]),
    ("Quest screen", "DepartureView.swift", [
        ("Eyebrow", "Daily quest / Back", "departing / returned"),
        ("Title", "{quest name}", "fallback “Quest”"),
        ("Body", "{depart bubble} / {return bubble}", "dialogue"),
        ("Under the path · returned, unclaimed", "Tap the cache.", "gold"),
        ("Under the path · otherwise", "{quest subtext}", ""),
        ("Countdown", "H:MM:SS → Back", "while away"),
        ("Cache button label", "Open the cache / What might be found", "accessibility"),
        ("Loot popover eyebrow", "Might be found down there", "lists item name + rarity"),
        ("Loot popover · empty", "Nobody knows.", ""),
        ("Dismiss button", "Got it / Later", "filled / quiet when a cache waits"),
    ]),
    ("Claim modal", "DepartureView.swift · ClaimMoment", [
        ("Eyebrow", "{tier} cache", "common / uncommon / rare; fallback “Cache”"),
        ("New item", "{item name} · {RARITY} · {item description}", "180 pt still"),
        ("Duplicate (trade-in) label", "Already yours", ""),
        ("Duplicate (trade-in) line", "Traded in for +{n} XP.", "fallback “Traded in for XP.”"),
        ("Nothing new · title", "Nothing new in it", "pool exhausted"),
        ("Nothing new · line", "Everything down there you already own. The walk still counts.", ""),
        ("Button", "Claim", "filled"),
    ]),
    ("Reward moment (after Claim)", "RewardMoment.swift", [
        ("Eyebrow", "Back from the quest", "Level up / Goal complete / Logged for other receipts"),
        ("Headline", "+{n} XP / Level {n}", ""),
        ("Body", "{return bubble}", "dialogue"),
        ("Unlocks", "Unlocked: {reward names}", ""),
        ("Button", "Continue", ""),
    ]),
    ("Local notification", "QuestNotifications.swift", [
        ("Title", "{character name} is back", "fallback “Your character”"),
        ("Body", "{first away bubble}", "dialogue"),
    ]),
    ("Room · inventory", "RoomView.swift", [
        ("Empty state", "Nothing yet. The Under City gives things to people who come back for them.", ""),
    ]),
    ("Ledger", "AppState.swift", [
        ("Quest row title", "{quest name}", ""),
        ("Goal row title", "{goal title}", "“{target}” stripped"),
        ("Bond row title", "The bond", ""),
    ]),
]
out.append("<h3>Shared quest chrome</h3><div class='wrap'><table><tr><th>Screen</th><th>Element</th><th>Copy</th><th>Notes</th></tr>")
for screen, file, rows in chrome:
    for k, (el, copy, note) in enumerate(rows):
        first = f"<strong>{e(screen)}</strong><br><span class='meta'>{e(file)}</span>" if k == 0 else ""
        out.append(f"<tr><td>{first}</td><td class='where'>{e(el)}</td><td class='copy'>{e(copy)}</td><td class='where'>{e(note)}</td></tr>")
out.append("</table></div></section>")

# 3. Daily goals
slots = [("primary", "Primary (one a day; training-day or rest-day pool)"), ("secondary", "Secondary (learning, mind, creative)"), ("small_win", "Small wins")]
def rule(r):
    t = r["type"]
    if t == "activity_family": return f"{r['family_id']} · {r['min_minutes']} min logged"
    if t == "workout_sets": return f"{r['count']} sets logged"
    if t == "steps": return f"{r['base']} steps + {r['per_level']}/level"
    return "manual tick"
out.append(f"""<section id="goals">
<h2>3 · Daily goals <span class="count">{len(goals)}</span> templates</h2>
<p class="lede">The title is the goal's name on the card and in the ledger. Lines are the companion's one-liner under the title; one is picked per day and rotates. <span class="var">{{target}}</span> fills in from the rule.</p>""")
for slot, label in slots:
    rows = [g for g in goals if g["slot"] == slot]
    out.append(f"<h3>{e(label)} · {len(rows)}</h3><div class='wrap'><table><tr><th>Title</th><th>Lines</th><th>Attribute</th><th>Completes when</th></tr>")
    for g in rows:
        lines = "".join(f"<li>{e(l)}</li>" for l in g["lines"])
        out.append(f"<tr><td class='copy'><strong>{e(g['title'])}</strong><br><span class='meta'>{e(g['id'])}</span></td><td class='copy'><ul class='lines'>{lines}</ul></td><td>{e(attrs.get(g['attribute_id'], g['attribute_id']))}</td><td class='where'>{e(rule(g['rule']))}</td></tr>")
    out.append("</table></div>")
out.append("</section></main>")
open(out_path, "w").write("\n".join(out))
print(f"wrote {out_path}: {len(items)} items ({len(missing)} without description), {len(quests)} quests, {len(goals)} goals")
