#!/usr/bin/env python3
"""Generate App/Sources/Theme/NeoTokyoTokens.swift from Content/v1/design-tokens.json.

Run after any token change. CI fails if the generated file is stale (see .github/workflows).
"""
import json, sys

SRC = "Content/v1/design-tokens.json"
DST = "App/Sources/Theme/NeoTokyoTokens.swift"
t = json.load(open(SRC))

def swift_name(s):
    parts = s.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])

def color_line(name, hexv, comment=""):
    r, g, b = (int(hexv[i:i+2], 16) / 255 for i in (1, 3, 5))
    c = f"  // {comment}" if comment else ""
    return f"        public static let {name} = Color(.sRGB, red: {r:.4f}, green: {g:.4f}, blue: {b:.4f}, opacity: 1){c}"

lines = [
    "// GENERATED by Tools/generate_theme_swift.py from Content/v1/design-tokens.json — do not edit.",
    f"// theme_id: {t['theme_id']}  content_version: {t['content_version']}",
    "import SwiftUI",
    "",
    "public enum NeoTokyo {",
    f"    public static let contentVersion = \"{t['content_version']}\"",
    "",
    "    public enum Surface {",
]
for k, v in t["surface"].items(): lines.append(color_line(swift_name(k), v["hex"], v["hex"]))
lines += ["    }", "", "    public enum Text {"]
for k, v in t["text"].items(): lines.append(color_line(swift_name(k), v["hex"], v["hex"]))
lines += ["    }", "", "    public enum Accent {"]
for k, v in t["accent"].items():
    lines.append(color_line(swift_name(k), v["hex"], v["hex"]))
    lines.append(color_line(swift_name(k) + "Dim", v["dim"], v["dim"]))
lines += ["    }", "", "    public enum Attribute {"]
for k, v in t["attribute"].items(): lines.append(color_line(swift_name(k), v["hex"], v["hex"]))
lines += ["", "        /// Color for an attribute slug from the content bundle; falls back to secondary text.",
          "        public static func color(for id: String) -> Color {",
          "            switch id {"]
for k in t["attribute"]: lines.append(f"            case \"{k}\": return {swift_name(k)}")
lines += ["            default: return NeoTokyo.Text.secondary", "            }", "        }", "    }", ""]
lines += ["    /// Which accent plays which role (doc 19). Views pick by role, not by hue.",
          "    public enum Hierarchy {",
          f"        public static let primary = Accent.{swift_name(t['hierarchy']['primary'])}",
          f"        public static let primaryDim = Accent.{swift_name(t['hierarchy']['primary'])}Dim",
          f"        public static let fallback = Accent.{swift_name(t['hierarchy']['fallback'][0])}",
          f"        public static let fallback2 = Accent.{swift_name(t['hierarchy']['fallback'][1])}",
          f"        public static let tertiary = Accent.{swift_name(t['hierarchy']['tertiary'])}",
          f"        public static let destructive = Accent.{swift_name(t['hierarchy']['destructive'])}",
          "    }", "",
          "    /// Font PostScript names and the type scale. Fonts are bundled from App/Resources/Fonts.",
          "    public enum Typeface {"]
for k, v in t["type"]["postscript"].items(): lines.append(f"        public static let {swift_name(k)} = \"{v}\"")
for k, v in t["type"]["scale"].items(): lines.append(f"        public static let {swift_name(k)}: CGFloat = {v}")
lines += ["    }", "", "    public enum Backdrop {"]
for k, v in t["backdrop_palettes"].items():
    shades = ", ".join(f"Color(.sRGB, red: {int(h[1:3],16)/255:.4f}, green: {int(h[3:5],16)/255:.4f}, blue: {int(h[5:7],16)/255:.4f}, opacity: 1)" for h in v["shades"])
    lines.append(f"        public static let {swift_name(k)}: [Color] = [{shades}]")
lines += ["    }", "", "    public enum Radius {"]
for k, v in t["radius"].items(): lines.append(f"        public static let {swift_name(k)}: CGFloat = {v}")
lines += ["    }", "", "    public enum Spacing {"]
for k, v in t["spacing"].items(): lines.append(f"        public static let {swift_name(k)}: CGFloat = {v}")
lines += ["    }", "", "    public enum Motion {"]
for k, v in t["motion"].items(): lines.append(f"        public static let {swift_name(k)}: Double = {v}")
lines += ["    }", "}", ""]

out = "\n".join(lines)
if "--check" in sys.argv:
    cur = open(DST).read()
    if cur != out:
        print(f"{DST} is stale; run python3 Tools/generate_theme_swift.py"); sys.exit(1)
    print("theme up to date"); sys.exit(0)
import os; os.makedirs(os.path.dirname(DST), exist_ok=True)
open(DST, "w").write(out); print("wrote", DST)
